schedules:
    # UTC time - being scheduled as 12h - 20h
  - cron: '0 11,19 * * *'
    displayName: Scheduled e2e tests
    branches:
      include:
        - dev
    always: true

trigger:
  - dev

pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: npm run test
  displayName: 'Run tests'
  env:
    CI: 'true'
  # continue task even if tests failed or went on error, to publish the current test results
  continueOnError: true
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true