schedules:
    # UTC time - being scheduled as 12h - 20h
  - cron: '0 11,19 * * *'
    displayName: Scheduled e2e tests
    branches:
      include:
        - dev
    always: true

trigger:
  - dev

pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
    
- script: npm ci
  displayName: 'npm ci'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'
- script: npm run build
  displayName: 'Build'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'
- script: npm run test:e2e
  displayName: 'Run Playwright tests'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'
  #Needed to run the publish test results task
  continueOnError: true
    
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'dummy-test-project/test-results/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true