schedules:
  - cron: '0 12,20 * * *'
    displayName: Scheduled e2e tests
    branches:
      include:
        - dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'

- task: Npm@1
  name: CompileApplication
  inputs:
    command: 'custom'
    customCommand: 'run build-only'
    workingDir: 'dummy-test-project'
    
- script: npm ci
  displayName: 'npm ci'
  workingDirectory: dummy-test-project
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
  workingDirectory: dummy-test-project
- script: npx playwright test
  displayName: 'Run Playwright tests'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    searchFolder: 'dummy-test-project/test-results'
    testResultsFormat: 'JUnit'
    testResultsFiles: 'e2e-junit-results.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'My End-To-End Tests'
  condition: succeededOrFailed()
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: dummy-test-project/playwright-report
    artifact: playwright-report
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
