schedules:
  - cron: '0 12,20 * * *'
    displayName: Scheduled e2e tests
    branches:
      include:
        - dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
    
- script: npm ci
  displayName: 'npm ci'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'
- script: npm run test:e2e
  displayName: 'Run Playwright tests'
  workingDirectory: dummy-test-project
  env:
    CI: 'true'